language: python

python:
 - "3.5"
 - "nightly"

services:
 - redis-server
 - elasticsearch

install:
 - pip install -r requirements.txt -r requirements-test.txt
 - pip install coveralls

before_script:
  - psql -c 'create database mygpo_test;' -U postgres

script:
  coverage run --branch --source=mygpo ./manage.py test

after_script:
  - coveralls

env:
 - DATABASE_URL="postgres://postgres@localhost/mygpo_test"

sudo: false
